id: baseline-vit-b16
pretrained: /content/drive/MyDrive/AI4VN/runs/ViT-2020_11_23-04_05_57/best_metric_Accuracy.pth
seed: 42
model:
    name: BaselineClassifier
    args:
        nclasses: 9
        extractor_cfg:
            name: VisionTransformer
            args:
                pretrained: ViT-B_16-224.npz
                version: ViT-B_16

dataset:
  csv: test.csv        
  batch_size: 32
    